version: "3.3"
services:
  database:
    build: database/
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=workhours
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    restart: always
    volumes:
      - ./database-data:/var/lib/mysql

  web:
    build: web/
    depends_on:
      - database
    ports:
      - 80:80
    restart: always